# Generated by Django 4.1.2 on 2023-01-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, max_length=200, null=True)),
                ('discription', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
