# Generated by Django 4.1.2 on 2023-01-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tech_app', '0002_registerdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
