# Generated by Django 4.1.2 on 2023-01-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tech_app', '0003_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
