# Generated by Django 4.1.2 on 2023-01-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tech_app', '0004_alter_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aname', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=12)),
                ('message', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
