# Generated by Django 4.1.2 on 2023-01-04 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tech_app', '0006_team'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='Teams',
        ),
    ]
