# Generated by Django 4.1.2 on 2023-01-04 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tech_app', '0007_rename_team_teams'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teams',
            old_name='image',
            new_name='images',
        ),
    ]
