# Generated by Django 4.1.2 on 2023-01-08 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tech_app', '0013_servicebooking_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebooking',
            name='service',
        ),
        migrations.AddField(
            model_name='detailservice',
            name='slot_status',
            field=models.CharField(default='Pending', max_length=200),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='booked_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 8, 15, 12, 15, 943751)),
        ),
    ]
