# Generated by Django 4.1.2 on 2023-01-08 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tech_app', '0018_remove_detailservice_service_detail_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebooking',
            name='service_detail_name',
        ),
        migrations.RemoveField(
            model_name='servicebooking',
            name='time_required',
        ),
        migrations.AddField(
            model_name='service',
            name='service_detail_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='slot_status',
            field=models.CharField(default='Pending', max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='time_required',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='booked_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 8, 15, 39, 50, 936570)),
        ),
    ]
