# Generated by Django 4.1.2 on 2023-01-08 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tech_app', '0020_alter_servicebooking_booked_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicestatusdetail',
            name='payment_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='servicestatusdetail',
            name='payment_request_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='servicestatusdetail',
            name='payment_status',
            field=models.CharField(default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='booked_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 8, 18, 24, 43, 65928)),
        ),
    ]
