# Generated by Django 4.1.2 on 2023-01-09 07:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tech_app', '0022_remove_service_slot_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='booked_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 9, 7, 9, 56, 685742)),
        ),
        migrations.AlterField(
            model_name='servicestatusdetail',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='servicestatusdetail',
            name='images',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
