# Generated by Django 4.1.2 on 2023-01-11 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tech_app', '0023_alter_servicebooking_booked_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='booked_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 11, 6, 53, 54, 879780)),
        ),
    ]
