# Generated by Django 4.1.2 on 2023-01-11 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tech_app', '0028_rename_name_contact_c_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='c_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='booked_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 11, 8, 2, 58, 181957)),
        ),
    ]
