# Generated by Django 4.1.2 on 2023-01-11 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tech_app', '0031_rename_c_name_contact_cname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='cname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='booked_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 11, 8, 20, 5, 953064)),
        ),
    ]
