# Generated by Django 4.1.2 on 2023-01-11 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tech_app', '0033_alter_servicebooking_booked_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='cname',
            new_name='contactname',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='msg',
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='servicebooking',
            name='booked_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 11, 8, 26, 57, 618088)),
        ),
    ]
